package_rename_config:
  android:
    app_name: Brokeflix
    package_name: dev.rayat.brokeflix

  ios:
    app_name: Brokeflix

  windows:
    app_name: Brokeflix # Window title & Software name
    organization: "ZuLab" # Organization/Company name
    copyright_notice: "Copyright © 2026 ZuLab" # Legal copyright
    exe_name: "brokeflix" # Executable name (binary)
