name: ytsmovies
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_breadcrumb: ^1.0.1
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  infinite_scroll_pagination: ^4.1.0
  youtube_player_flutter: ^9.1.1
  cached_network_image: ^3.2.3
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  go_router: ^15.1.2
  dio: ^5.1.1
  freezed_annotation: ^3.0.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  dio_cache_interceptor: ^4.0.3
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  http_cache_hive_store: ^5.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.2.19
  change_app_package_name: ^1.1.0

  package_rename: ^1.2.0
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  hive_ce_generator: ^1.9.2
  flutter_unused_packages: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/logo-imdb.png
    - images/logo-YTS.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
